version: '2'
services:
    rabbitmqocaml-app:
        image: rabbitmqocaml
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_COUCHBASE_BOOTSTRAP_HOSTS=rabbitmqocaml-couchbase
            - SPRING_COUCHBASE_BUCKET_NAME=rabbitmqocaml
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    rabbitmqocaml-couchbase:
        extends:
            file: couchbase.yml
            service: rabbitmqocaml-couchbase
