version: '2'
services:
    rabbitmqocaml-couchbase:
        build:
            context: .
            dockerfile: couchbase/Couchbase.Dockerfile
        ports:
            - 8091:8091
            - 8092:8092
            - 8093:8093
            - 11210:11210
        environment:
            - TYPE=MASTER
            - BUCKET=rabbitmqocaml
    rabbitmqocaml-couchbase-node:
        build:
            context: .
            dockerfile: couchbase/Couchbase.Dockerfile
        environment:
            - TYPE=WORKER
            - BUCKET=rabbitmqocaml
            - COUCHBASE_MASTER=rabbitmqocaml-couchbase
            - AUTO_REBALANCE=false
